name: CICD
on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is the environment value where this workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
          - main

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "done code checkout from github"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build the code
        run: echo "Build completed"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test the code
        run: echo "Testing completed"

  deploy:
    if: inputs.environment == 'dev'
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy the code
        run: echo "Deploy completed"
