name: Devsecops End to End

on:
  push:
    brnaches: [main]

# (Continuous Integration with security check)
jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secrets-scan:
    uses: ./.github/workflows/secrets-scan.yml
    secrets: inherit
  
  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml
      
  docker-scan:
    uses: ./.github/workflows/docker-lint.yml
  
  # (Deploy once all the builds are completed with secuity check)
  build:
    needs: [code-quality, secrets-scan, dependency-scan, docker-scan]
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit
