# This script helps you to write first yaml file
---
name: Hello workflow
on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to umesh
        run: echo "Hello Umesh"
      - name: say hello to username
        run: echo "Hello $USER"
        
  versions:
    runs-on: ubuntu-latest
    steps:
      - name: check version of python and docker
        run: |
          docker --version
          python --version
